// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9BRgHBHS2KLI5NMG21gfDvUm0MnG4VAY',
    appId: '1:439707684384:ios:e238cdfd93967e93d9f645',
    messagingSenderId: '439707684384',
    projectId: 'location-tracker-77cf7',
    storageBucket: 'location-tracker-77cf7.firebasestorage.app',
    iosBundleId: 'com.example.locationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi047Zp_4dywuxebV-WQ6e8FLjcFT6Tec',
    appId: '1:439707684384:web:1c147d18e3f87402d9f645',
    messagingSenderId: '439707684384',
    projectId: 'location-tracker-77cf7',
    authDomain: 'location-tracker-77cf7.firebaseapp.com',
    storageBucket: 'location-tracker-77cf7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi047Zp_4dywuxebV-WQ6e8FLjcFT6Tec',
    appId: '1:439707684384:web:1c147d18e3f87402d9f645',
    messagingSenderId: '439707684384',
    projectId: 'location-tracker-77cf7',
    authDomain: 'location-tracker-77cf7.firebaseapp.com',
    storageBucket: 'location-tracker-77cf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9BRgHBHS2KLI5NMG21gfDvUm0MnG4VAY',
    appId: '1:439707684384:ios:e238cdfd93967e93d9f645',
    messagingSenderId: '439707684384',
    projectId: 'location-tracker-77cf7',
    storageBucket: 'location-tracker-77cf7.firebasestorage.app',
    iosBundleId: 'com.example.locationTracker',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClOz3loSGtBiyAHUfEHxvbH-ZqTc6m838',
    appId: '1:439707684384:android:9950f2547a3e725bd9f645',
    messagingSenderId: '439707684384',
    projectId: 'location-tracker-77cf7',
    storageBucket: 'location-tracker-77cf7.firebasestorage.app',
  );

}